### ISSUE TITLE
Example server `--ssl` flag is broken

### ISSUE THREAD

**Issue by mehaase** [HyperionGray/trio-websocket#25]
The example server cannot run with SSL enabled. This looks like a regression introduced in #10. Now that we have a test suite, I can write a test for SSL and then fix this issue.

```(venv) /home/mhaase/code/trio-websocket (remove_client_class) $ python examples/server.py 127.0.0.1 8000 --ssl
INFO:root:Starting websocket server…
Traceback (most recent call last):
  File "examples/server.py", line 67, in <module>
    trio.run(main, parse_args())
  File "/home/mhaase/code/trio-websocket/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 1328, in run
    raise runner.main_task_outcome.error
  File "examples/server.py", line 49, in main
    await server.listen()
  File "/home/mhaase/code/trio-websocket/trio_websocket/__init__.py", line 491, in listen
    self._port = listener.socket.getsockname()[1]
AttributeError: 'SSLListener' object has no attribute 'socket'
```

**Comment by mehaase** [comment]
This was covered by tests and fixed in #2.
